name: Daily Commit Workflow

on:
  schedule:
    # Runs daily at 12:00 AM UTC
    - cron: '0 0 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make changes
      run: |
        echo "Automated commit at $(date)" >> daily-log.txt

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "23f2003642@ds.study.iitm.ac.in"

    - name: Commit changes
      run: |
        git add daily-log.txt
        git commit -m "Automated commit on $(date)"
        git push
